# Generated by Django 3.2.3 on 2021-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('Product_Date', models.DateField()),
            ],
        ),
    ]
